-- TABLE CREATION SCRIPTS FOR TELCO PROJECT

-- Drop tables if they already exist.
-- If these tables do not exist yet, Oracle may show an error for these lines.
-- This is normal when running the script for the first time.

DROP TABLE MONTHLY_STATS;
DROP TABLE CUSTOMERS;
DROP TABLE TARIFFS;

-- TARIFFS table stores tariff/package information.
CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10,2) NOT NULL,
    DATA_LIMIT NUMBER(10,2) NOT NULL,
    MINUTE_LIMIT NUMBER NOT NULL,
    SMS_LIMIT NUMBER NOT NULL
);

-- CUSTOMERS table stores customer information.
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER NOT NULL,

    CONSTRAINT FK_CUSTOMERS_TARIFFS
        FOREIGN KEY (TARIFF_ID)
        REFERENCES TARIFFS(TARIFF_ID)
);

-- MONTHLY_STATS table stores monthly usage and payment status information.
-- A foreign key is not added to CUSTOMER_ID here because the sample data IDs
-- in MONTHLY_STATS and CUSTOMERS appear to use different numbering ranges.
CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    DATA_USAGE NUMBER(10,2) DEFAULT 0 NOT NULL,
    MINUTE_USAGE NUMBER DEFAULT 0 NOT NULL,
    SMS_USAGE NUMBER DEFAULT 0 NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('PAID', 'LATE', 'UNPAID'))
);

-- Indexes for faster searching, filtering, and joining.
CREATE INDEX IDX_CUSTOMERS_TARIFF_ID
ON CUSTOMERS(TARIFF_ID);

CREATE INDEX IDX_CUSTOMERS_SIGNUP_DATE
ON CUSTOMERS(SIGNUP_DATE);

CREATE INDEX IDX_MONTHLY_STATS_CUSTOMER_ID
ON MONTHLY_STATS(CUSTOMER_ID);

CREATE INDEX IDX_MONTHLY_STATS_PAYMENT_STATUS
ON MONTHLY_STATS(PAYMENT_STATUS);