-- TABLE CREATION SCRIPTS FOR TELCO PROJECT
-- This script creates the required tables, constraints, and indexes for the Telco Project.
-- The tables are designed according to the provided CSV files.

DROP TABLE MONTHLY_STATS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE TARIFFS CASCADE CONSTRAINTS;


CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10,2) NOT NULL,
    DATA_LIMIT NUMBER(10,2) NOT NULL,
    MINUTE_LIMIT NUMBER NOT NULL,
    SMS_LIMIT NUMBER NOT NULL
);


CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER NOT NULL,

    CONSTRAINT FK_CUSTOMERS_TARIFFS
        FOREIGN KEY (TARIFF_ID)
        REFERENCES TARIFFS(TARIFF_ID)
);


CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    DATA_USAGE NUMBER(10,2) DEFAULT 0 NOT NULL,
    MINUTE_USAGE NUMBER DEFAULT 0 NOT NULL,
    SMS_USAGE NUMBER DEFAULT 0 NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_MONTHLY_STATS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('PAID', 'LATE', 'UNPAID'))
);


CREATE INDEX IDX_CUSTOMERS_TARIFF_ID
ON CUSTOMERS(TARIFF_ID);

CREATE INDEX IDX_CUSTOMERS_SIGNUP_DATE
ON CUSTOMERS(SIGNUP_DATE);

CREATE INDEX IDX_MONTHLY_STATS_CUSTOMER_ID
ON MONTHLY_STATS(CUSTOMER_ID);

CREATE INDEX IDX_MONTHLY_STATS_PAYMENT_STATUS
ON MONTHLY_STATS(PAYMENT_STATUS);